import InputHorizontal from "@/components/custom/input-horizontal";
import HeaderTitle from "@/components/navbar/header-title";
import React from "react";
import { useForm } from "react-hook-form";

export default function CustomerInfo() {
    const {
        register,
        handleSubmit,
        watch,
        formState: { errors },
        setValue
    } = useForm<SubmitInput>()

    const [isEditable, setIsEditable] = React.useState<boolean>(false);

    return (
        <>
            <HeaderTitle
                className="gap-0"
                title="ข้อมูลส่วนตัว"
            />
            <div className="grid grid-cols-3">
                <InputHorizontal
                    label="ประเภทลูกค้า"
                    defaultValue="1 - บุคคลธรรมดาในประเทศ"
                    isEditable={isEditable}
                    register={register}
                    name="typeCustomer"
                    isRequired
                />
                <InputHorizontal
                    label="ประเภทหลักฐานลูกค้า"
                    defaultValue="บัตรประจำตัวประชาชน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="เลขที่บัตร"
                    defaultValue="310012320981"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ประเทศที่ออกบัตร"
                    defaultValue="ไทย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ประเทศเจ้าของสัญชาติ"
                    defaultValue="ไทย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="วันที่หมดอายุบัตร (ค.ศ.)"
                    defaultValue="11/10/2030"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="คำนำหน้า"
                    defaultValue="น.ส."
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ชื่อ (ภาษาไทย)"
                    defaultValue="จิรารัชย์"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="นามสกุล (ภาษาไทย)"
                    defaultValue="อังคสุวรรณศิริ"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label=""
                    defaultValue=""
                    register={register}
                    name=""
                />
                <InputHorizontal
                    label="ชื่อ (ภาษาอังกฤษ)"
                    defaultValue="Jirarach"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="นามสกุล (ภาษาอังกฤษ)"
                    defaultValue="Angkasuwansi"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="เพศ"
                    defaultValue="หญิง"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="วัน/เดือน/ปีเกิด (ค.ศ.)"
                    defaultValue="12/10/1972"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
            </div>
            <HeaderTitle
                className="gap-0"
                title="สถานภาพการสมรส"
            />
            <div className="grid grid-cols-3">
                <InputHorizontal
                    label="สถานภาพ"
                    defaultValue="สมรส"
                    isEditable={isEditable}
                    register={register}
                    name="status"
                    isRequired
                />
                <InputHorizontal
                    label="ประเภทหลักฐานลูกค้า"
                    defaultValue="บัตรประจำตัวประชาชน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="เลขที่บัตร"
                    defaultValue="310012320981"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="คำนำหน้า"
                    defaultValue="นาย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ชื่อคู่สมรส"
                    defaultValue="อนันกร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="นามสกุลคู่สมรส"
                    defaultValue="อังคสุวรรณศิริ"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
            </div>
            <HeaderTitle
                className="gap-0"
                title="ที่อยู่ตามประเภทหลักฐาน"
            />
            <div className="grid grid-cols-3">
                <InputHorizontal
                    label="เลขที่"
                    defaultValue="111/11"
                    isEditable={isEditable}
                    register={register}
                    name="status"
                />
                <InputHorizontal
                    label="หมู่ที่"
                    defaultValue="1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="หมู่บ้าน / อาคาร"
                    defaultValue="รวยพันล้าน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ห้อง"
                    defaultValue="515"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ชั้น"
                    defaultValue="5"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ตรอก / ซอย"
                    defaultValue="รวยพันล้าน 1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ถนน"
                    defaultValue="พหลโยธิน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ประเทศ"
                    defaultValue="ไทย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="รหัสไปรษณีย์"
                    defaultValue="10900"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="จังหวัด"
                    defaultValue="กรุงเทพมหานคร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="อำเภอ / เขต"
                    defaultValue="จตุจักร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ตำบล / แขวง"
                    defaultValue="เสนานิคม"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
            </div>

            <HeaderTitle
                className="gap-0"
                title="ที่อยู่ปัจจุบันที่ติดต่อได้"
            />
            <div className="grid grid-cols-3">
                <InputHorizontal
                    label="เลขที่"
                    defaultValue="111/11"
                    isEditable={isEditable}
                    register={register}
                    name="status"
                />
                <InputHorizontal
                    label="หมู่ที่"
                    defaultValue="1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="หมู่บ้าน / อาคาร"
                    defaultValue="รวยพันล้าน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ห้อง"
                    defaultValue="515"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ชั้น"
                    defaultValue="5"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ตรอก / ซอย"
                    defaultValue="รวยพันล้าน 1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ถนน"
                    defaultValue="พหลโยธิน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ประเทศ"
                    defaultValue="ไทย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="รหัสไปรษณีย์"
                    defaultValue="10900"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="จังหวัด"
                    defaultValue="กรุงเทพมหานคร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="อำเภอ / เขต"
                    defaultValue="จตุจักร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ตำบล / แขวง"
                    defaultValue="เสนานิคม"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
            </div>
            <HeaderTitle
                className="gap-0"
                title="อาชีพ"
            />
            <span className="mx-4">76-อื่นๆ (โปรดระบุ) Other (Please specify) อื่นๆ Other …............................... (910.99)</span>
            <div className="grid grid-cols-3">
                <InputHorizontal
                    label="เลขที่"
                    defaultValue="111/11"
                    isEditable={isEditable}
                    register={register}
                    name="status"
                />
                <InputHorizontal
                    label="หมู่ที่"
                    defaultValue="1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="หมู่บ้าน / อาคาร"
                    defaultValue="รวยพันล้าน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ห้อง"
                    defaultValue="515"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ชั้น"
                    defaultValue="5"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ตรอก / ซอย"
                    defaultValue="รวยพันล้าน 1"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ถนน"
                    defaultValue="พหลโยธิน"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                />
                <InputHorizontal
                    label="ประเทศ"
                    defaultValue="ไทย"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="รหัสไปรษณีย์"
                    defaultValue="10900"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="จังหวัด"
                    defaultValue="กรุงเทพมหานคร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="อำเภอ / เขต"
                    defaultValue="จตุจักร"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
                <InputHorizontal
                    label="ตำบล / แขวง"
                    defaultValue="เสนานิคม"
                    isEditable={isEditable}
                    register={register}
                    name="riskGroup"
                    isRequired
                />
            </div>
            <HeaderTitle
                className="gap-0"
                title="สถานภาพทางการเมือง"
            />
            <div className="flex flex-col">
                <span className="mx-4 font-bold">ท่านเป็นผู้มีสถานภาพทางการเมืองหรือเป็นสมาชิกในครอบครัว หรือเป็นผู้ใกล้ชิดกับบุคคลผู้มีสถานภาพทางการเมืองหรือไม่ * </span>
                <span className="mx-4">ไม่มี</span>
            </div>
        </>
    )
}

interface SubmitInput {
    riskGroupSummary: string;
}