/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.320
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountInfoResponse } from './AccountInfoResponse';
import {
    AccountInfoResponseFromJSON,
    AccountInfoResponseFromJSONTyped,
    AccountInfoResponseToJSON,
} from './AccountInfoResponse';

/**
 * 
 * @export
 * @interface AccountInfoResponseDataResponse
 */
export interface AccountInfoResponseDataResponse {
    /**
     * 
     * @type {number}
     * @memberof AccountInfoResponseDataResponse
     */
    status?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof AccountInfoResponseDataResponse
     */
    errors?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {string}
     * @memberof AccountInfoResponseDataResponse
     */
    message?: string | null;
    /**
     * 
     * @type {AccountInfoResponse}
     * @memberof AccountInfoResponseDataResponse
     */
    data?: AccountInfoResponse | null;
}

/**
 * Check if a given object implements the AccountInfoResponseDataResponse interface.
 */
export function instanceOfAccountInfoResponseDataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountInfoResponseDataResponseFromJSON(json: any): AccountInfoResponseDataResponse {
    return AccountInfoResponseDataResponseFromJSONTyped(json, false);
}

export function AccountInfoResponseDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoResponseDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : AccountInfoResponseFromJSON(json['data']),
    };
}

export function AccountInfoResponseDataResponseToJSON(value?: AccountInfoResponseDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'message': value.message,
        'data': AccountInfoResponseToJSON(value.data),
    };
}

