/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.330
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressMaster
 */
export interface AddressMaster {
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    provinceCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    provinceNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    amphurCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    amphurNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    tambonCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    tambonNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressMaster
     */
    postCodeMain?: string | null;
}

/**
 * Check if a given object implements the AddressMaster interface.
 */
export function instanceOfAddressMaster(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressMasterFromJSON(json: any): AddressMaster {
    return AddressMasterFromJSONTyped(json, false);
}

export function AddressMasterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressMaster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provinceCode': !exists(json, 'provinceCode') ? undefined : json['provinceCode'],
        'provinceNameTh': !exists(json, 'provinceNameTh') ? undefined : json['provinceNameTh'],
        'amphurCode': !exists(json, 'amphurCode') ? undefined : json['amphurCode'],
        'amphurNameTh': !exists(json, 'amphurNameTh') ? undefined : json['amphurNameTh'],
        'tambonCode': !exists(json, 'tambonCode') ? undefined : json['tambonCode'],
        'tambonNameTh': !exists(json, 'tambonNameTh') ? undefined : json['tambonNameTh'],
        'postCodeMain': !exists(json, 'postCodeMain') ? undefined : json['postCodeMain'],
    };
}

export function AddressMasterToJSON(value?: AddressMaster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provinceCode': value.provinceCode,
        'provinceNameTh': value.provinceNameTh,
        'amphurCode': value.amphurCode,
        'amphurNameTh': value.amphurNameTh,
        'tambonCode': value.tambonCode,
        'tambonNameTh': value.tambonNameTh,
        'postCodeMain': value.postCodeMain,
    };
}

