/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.350
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BeneficiaryInfoRequest
 */
export interface BeneficiaryInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    addressTypeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    addressTypeDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    addressNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    buildingOrVillage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    floor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    roomNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    moo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    soi?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    provinceCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    provinceNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    districtCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    districtNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    subDistrictCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    subDistrictNameTh?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    countryDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    customAddress1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    customAddress2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    customAddress3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    mobileNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    telephoneNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    officeNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BeneficiaryInfoRequest
     */
    isOwner?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryFirstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryLastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    relationDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryRelationshipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryRelationshipOther?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    referenceTypeDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryExpireDate?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BeneficiaryInfoRequest
     */
    beneficiaryNeverExpire?: boolean | null;
}

/**
 * Check if a given object implements the BeneficiaryInfoRequest interface.
 */
export function instanceOfBeneficiaryInfoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BeneficiaryInfoRequestFromJSON(json: any): BeneficiaryInfoRequest {
    return BeneficiaryInfoRequestFromJSONTyped(json, false);
}

export function BeneficiaryInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeneficiaryInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressTypeCode': !exists(json, 'addressTypeCode') ? undefined : json['addressTypeCode'],
        'addressTypeDesc': !exists(json, 'addressTypeDesc') ? undefined : json['addressTypeDesc'],
        'addressNo': !exists(json, 'addressNo') ? undefined : json['addressNo'],
        'buildingOrVillage': !exists(json, 'buildingOrVillage') ? undefined : json['buildingOrVillage'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'roomNo': !exists(json, 'roomNo') ? undefined : json['roomNo'],
        'moo': !exists(json, 'moo') ? undefined : json['moo'],
        'soi': !exists(json, 'soi') ? undefined : json['soi'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'provinceCode': !exists(json, 'provinceCode') ? undefined : json['provinceCode'],
        'provinceNameTh': !exists(json, 'provinceNameTh') ? undefined : json['provinceNameTh'],
        'districtCode': !exists(json, 'districtCode') ? undefined : json['districtCode'],
        'districtNameTh': !exists(json, 'districtNameTh') ? undefined : json['districtNameTh'],
        'subDistrictCode': !exists(json, 'subDistrictCode') ? undefined : json['subDistrictCode'],
        'subDistrictNameTh': !exists(json, 'subDistrictNameTh') ? undefined : json['subDistrictNameTh'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'countryDesc': !exists(json, 'countryDesc') ? undefined : json['countryDesc'],
        'zipCode': !exists(json, 'zipCode') ? undefined : json['zipCode'],
        'customAddress1': !exists(json, 'customAddress1') ? undefined : json['customAddress1'],
        'customAddress2': !exists(json, 'customAddress2') ? undefined : json['customAddress2'],
        'customAddress3': !exists(json, 'customAddress3') ? undefined : json['customAddress3'],
        'mobileNo': !exists(json, 'mobileNo') ? undefined : json['mobileNo'],
        'telephoneNo': !exists(json, 'telephoneNo') ? undefined : json['telephoneNo'],
        'officeNo': !exists(json, 'officeNo') ? undefined : json['officeNo'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'isOwner': !exists(json, 'isOwner') ? undefined : json['isOwner'],
        'beneficiaryFirstName': !exists(json, 'beneficiaryFirstName') ? undefined : json['beneficiaryFirstName'],
        'beneficiaryLastName': !exists(json, 'beneficiaryLastName') ? undefined : json['beneficiaryLastName'],
        'relationDesc': !exists(json, 'relationDesc') ? undefined : json['relationDesc'],
        'beneficiaryRelationshipCode': !exists(json, 'beneficiaryRelationshipCode') ? undefined : json['beneficiaryRelationshipCode'],
        'beneficiaryRelationshipOther': !exists(json, 'beneficiaryRelationshipOther') ? undefined : json['beneficiaryRelationshipOther'],
        'referenceTypeDesc': !exists(json, 'referenceTypeDesc') ? undefined : json['referenceTypeDesc'],
        'beneficiaryType': !exists(json, 'beneficiaryType') ? undefined : json['beneficiaryType'],
        'beneficiaryNo': !exists(json, 'beneficiaryNo') ? undefined : json['beneficiaryNo'],
        'beneficiaryExpireDate': !exists(json, 'beneficiaryExpireDate') ? undefined : json['beneficiaryExpireDate'],
        'beneficiaryNeverExpire': !exists(json, 'beneficiaryNeverExpire') ? undefined : json['beneficiaryNeverExpire'],
    };
}

export function BeneficiaryInfoRequestToJSON(value?: BeneficiaryInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addressTypeCode': value.addressTypeCode,
        'addressTypeDesc': value.addressTypeDesc,
        'addressNo': value.addressNo,
        'buildingOrVillage': value.buildingOrVillage,
        'floor': value.floor,
        'roomNo': value.roomNo,
        'moo': value.moo,
        'soi': value.soi,
        'street': value.street,
        'provinceCode': value.provinceCode,
        'provinceNameTh': value.provinceNameTh,
        'districtCode': value.districtCode,
        'districtNameTh': value.districtNameTh,
        'subDistrictCode': value.subDistrictCode,
        'subDistrictNameTh': value.subDistrictNameTh,
        'countryCode': value.countryCode,
        'countryDesc': value.countryDesc,
        'zipCode': value.zipCode,
        'customAddress1': value.customAddress1,
        'customAddress2': value.customAddress2,
        'customAddress3': value.customAddress3,
        'mobileNo': value.mobileNo,
        'telephoneNo': value.telephoneNo,
        'officeNo': value.officeNo,
        'email': value.email,
        'isOwner': value.isOwner,
        'beneficiaryFirstName': value.beneficiaryFirstName,
        'beneficiaryLastName': value.beneficiaryLastName,
        'relationDesc': value.relationDesc,
        'beneficiaryRelationshipCode': value.beneficiaryRelationshipCode,
        'beneficiaryRelationshipOther': value.beneficiaryRelationshipOther,
        'referenceTypeDesc': value.referenceTypeDesc,
        'beneficiaryType': value.beneficiaryType,
        'beneficiaryNo': value.beneficiaryNo,
        'beneficiaryExpireDate': value.beneficiaryExpireDate,
        'beneficiaryNeverExpire': value.beneficiaryNeverExpire,
    };
}

