/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.332
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocReceiveAddressInfoModel } from './DocReceiveAddressInfoModel';
import {
    DocReceiveAddressInfoModelFromJSON,
    DocReceiveAddressInfoModelFromJSONTyped,
    DocReceiveAddressInfoModelToJSON,
} from './DocReceiveAddressInfoModel';
import type { EmergencyContactInfoModel } from './EmergencyContactInfoModel';
import {
    EmergencyContactInfoModelFromJSON,
    EmergencyContactInfoModelFromJSONTyped,
    EmergencyContactInfoModelToJSON,
} from './EmergencyContactInfoModel';

/**
 * 
 * @export
 * @interface ContactInfoRequest
 */
export interface ContactInfoRequest {
    /**
     * 
     * @type {number}
     * @memberof ContactInfoRequest
     */
    isAddressInfoType4SameType?: number;
    /**
     * 
     * @type {DocReceiveAddressInfoModel}
     * @memberof ContactInfoRequest
     */
    docReceiveAddressInfo?: DocReceiveAddressInfoModel | null;
    /**
     * 
     * @type {Array<EmergencyContactInfoModel>}
     * @memberof ContactInfoRequest
     */
    emergencyContactInfo?: Array<EmergencyContactInfoModel> | null;
}

/**
 * Check if a given object implements the ContactInfoRequest interface.
 */
export function instanceOfContactInfoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContactInfoRequestFromJSON(json: any): ContactInfoRequest {
    return ContactInfoRequestFromJSONTyped(json, false);
}

export function ContactInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAddressInfoType4SameType': !exists(json, 'isAddressInfoType4SameType') ? undefined : json['isAddressInfoType4SameType'],
        'docReceiveAddressInfo': !exists(json, 'docReceiveAddressInfo') ? undefined : DocReceiveAddressInfoModelFromJSON(json['docReceiveAddressInfo']),
        'emergencyContactInfo': !exists(json, 'emergencyContactInfo') ? undefined : (json['emergencyContactInfo'] === null ? null : (json['emergencyContactInfo'] as Array<any>).map(EmergencyContactInfoModelFromJSON)),
    };
}

export function ContactInfoRequestToJSON(value?: ContactInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAddressInfoType4SameType': value.isAddressInfoType4SameType,
        'docReceiveAddressInfo': DocReceiveAddressInfoModelToJSON(value.docReceiveAddressInfo),
        'emergencyContactInfo': value.emergencyContactInfo === undefined ? undefined : (value.emergencyContactInfo === null ? null : (value.emergencyContactInfo as Array<any>).map(EmergencyContactInfoModelToJSON)),
    };
}

