/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.330
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FinancialInfoModel } from './FinancialInfoModel';
import {
    FinancialInfoModelFromJSON,
    FinancialInfoModelFromJSONTyped,
    FinancialInfoModelToJSON,
} from './FinancialInfoModel';

/**
 * 
 * @export
 * @interface FinancialInfoResponse
 */
export interface FinancialInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof FinancialInfoResponse
     */
    corporateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialInfoResponse
     */
    referenceId?: string | null;
    /**
     * 
     * @type {FinancialInfoModel}
     * @memberof FinancialInfoResponse
     */
    financialInfo?: FinancialInfoModel | null;
}

/**
 * Check if a given object implements the FinancialInfoResponse interface.
 */
export function instanceOfFinancialInfoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FinancialInfoResponseFromJSON(json: any): FinancialInfoResponse {
    return FinancialInfoResponseFromJSONTyped(json, false);
}

export function FinancialInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'corporateId': !exists(json, 'corporateId') ? undefined : json['corporateId'],
        'referenceId': !exists(json, 'referenceId') ? undefined : json['referenceId'],
        'financialInfo': !exists(json, 'financialInfo') ? undefined : FinancialInfoModelFromJSON(json['financialInfo']),
    };
}

export function FinancialInfoResponseToJSON(value?: FinancialInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'corporateId': value.corporateId,
        'referenceId': value.referenceId,
        'financialInfo': FinancialInfoModelToJSON(value.financialInfo),
    };
}

