/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.332
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KycAttroneyInput
 */
export interface KycAttroneyInput {
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    titleCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    titleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    titleOther?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    referenceTypeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    referenceNo?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof KycAttroneyInput
     */
    referenceExpireDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof KycAttroneyInput
     */
    referenceNeverExpire?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    relationCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    relationOther?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    nationCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    tel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    mobile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    addressNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    moo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    buildingOrVillage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    roomNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    floor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    soi?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    tambonCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    amphurCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    provinceCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    postCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    customAddress1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    customAddress2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    customAddress3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KycAttroneyInput
     */
    productCode?: string | null;
}

/**
 * Check if a given object implements the KycAttroneyInput interface.
 */
export function instanceOfKycAttroneyInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KycAttroneyInputFromJSON(json: any): KycAttroneyInput {
    return KycAttroneyInputFromJSONTyped(json, false);
}

export function KycAttroneyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycAttroneyInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titleCode': !exists(json, 'titleCode') ? undefined : json['titleCode'],
        'titleName': !exists(json, 'titleName') ? undefined : json['titleName'],
        'titleOther': !exists(json, 'titleOther') ? undefined : json['titleOther'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'referenceTypeCode': !exists(json, 'referenceTypeCode') ? undefined : json['referenceTypeCode'],
        'referenceNo': !exists(json, 'referenceNo') ? undefined : json['referenceNo'],
        'referenceExpireDate': !exists(json, 'referenceExpireDate') ? undefined : (json['referenceExpireDate'] === null ? null : new Date(json['referenceExpireDate'])),
        'referenceNeverExpire': !exists(json, 'referenceNeverExpire') ? undefined : json['referenceNeverExpire'],
        'relationCode': !exists(json, 'relationCode') ? undefined : json['relationCode'],
        'relationOther': !exists(json, 'relationOther') ? undefined : json['relationOther'],
        'nationCode': !exists(json, 'nationCode') ? undefined : json['nationCode'],
        'tel': !exists(json, 'tel') ? undefined : json['tel'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'addressNo': !exists(json, 'addressNo') ? undefined : json['addressNo'],
        'moo': !exists(json, 'moo') ? undefined : json['moo'],
        'buildingOrVillage': !exists(json, 'buildingOrVillage') ? undefined : json['buildingOrVillage'],
        'roomNo': !exists(json, 'roomNo') ? undefined : json['roomNo'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'soi': !exists(json, 'soi') ? undefined : json['soi'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'tambonCode': !exists(json, 'tambonCode') ? undefined : json['tambonCode'],
        'amphurCode': !exists(json, 'amphurCode') ? undefined : json['amphurCode'],
        'provinceCode': !exists(json, 'provinceCode') ? undefined : json['provinceCode'],
        'postCode': !exists(json, 'postCode') ? undefined : json['postCode'],
        'customAddress1': !exists(json, 'customAddress1') ? undefined : json['customAddress1'],
        'customAddress2': !exists(json, 'customAddress2') ? undefined : json['customAddress2'],
        'customAddress3': !exists(json, 'customAddress3') ? undefined : json['customAddress3'],
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'productCode': !exists(json, 'productCode') ? undefined : json['productCode'],
    };
}

export function KycAttroneyInputToJSON(value?: KycAttroneyInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titleCode': value.titleCode,
        'titleName': value.titleName,
        'titleOther': value.titleOther,
        'name': value.name,
        'referenceTypeCode': value.referenceTypeCode,
        'referenceNo': value.referenceNo,
        'referenceExpireDate': value.referenceExpireDate === undefined ? undefined : (value.referenceExpireDate === null ? null : value.referenceExpireDate.toISOString()),
        'referenceNeverExpire': value.referenceNeverExpire,
        'relationCode': value.relationCode,
        'relationOther': value.relationOther,
        'nationCode': value.nationCode,
        'tel': value.tel,
        'mobile': value.mobile,
        'email': value.email,
        'addressNo': value.addressNo,
        'moo': value.moo,
        'buildingOrVillage': value.buildingOrVillage,
        'roomNo': value.roomNo,
        'floor': value.floor,
        'soi': value.soi,
        'street': value.street,
        'tambonCode': value.tambonCode,
        'amphurCode': value.amphurCode,
        'provinceCode': value.provinceCode,
        'postCode': value.postCode,
        'customAddress1': value.customAddress1,
        'customAddress2': value.customAddress2,
        'customAddress3': value.customAddress3,
        'countryCode': value.countryCode,
        'productCode': value.productCode,
    };
}

