/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.346
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KycGetAllOutput } from './KycGetAllOutput';
import {
    KycGetAllOutputFromJSON,
    KycGetAllOutputFromJSONTyped,
    KycGetAllOutputToJSON,
} from './KycGetAllOutput';

/**
 * 
 * @export
 * @interface KycGetAllOutputDataResponse
 */
export interface KycGetAllOutputDataResponse {
    /**
     * 
     * @type {number}
     * @memberof KycGetAllOutputDataResponse
     */
    status?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof KycGetAllOutputDataResponse
     */
    errors?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {string}
     * @memberof KycGetAllOutputDataResponse
     */
    message?: string | null;
    /**
     * 
     * @type {KycGetAllOutput}
     * @memberof KycGetAllOutputDataResponse
     */
    data?: KycGetAllOutput | null;
}

/**
 * Check if a given object implements the KycGetAllOutputDataResponse interface.
 */
export function instanceOfKycGetAllOutputDataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KycGetAllOutputDataResponseFromJSON(json: any): KycGetAllOutputDataResponse {
    return KycGetAllOutputDataResponseFromJSONTyped(json, false);
}

export function KycGetAllOutputDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycGetAllOutputDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : KycGetAllOutputFromJSON(json['data']),
    };
}

export function KycGetAllOutputDataResponseToJSON(value?: KycGetAllOutputDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'errors': value.errors,
        'message': value.message,
        'data': KycGetAllOutputToJSON(value.data),
    };
}

