/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.242
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttorneyInfoOutput } from './attorney-info-output';

/**
 * 
 * @export
 * @interface AttorneyInfoOutputListDataResponse
 */
export interface AttorneyInfoOutputListDataResponse {
    /**
     * 
     * @type {number}
     * @memberof AttorneyInfoOutputListDataResponse
     */
    'status'?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof AttorneyInfoOutputListDataResponse
     */
    'errors'?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {string}
     * @memberof AttorneyInfoOutputListDataResponse
     */
    'message'?: string | null;
    /**
     * 
     * @type {Array<AttorneyInfoOutput>}
     * @memberof AttorneyInfoOutputListDataResponse
     */
    'data'?: Array<AttorneyInfoOutput> | null;
}

