/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.267
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConsentDataDetailSave } from './consent-data-detail-save';

/**
 * 
 * @export
 * @interface ConsentSaveInput
 */
export interface ConsentSaveInput {
    /**
     * 
     * @type {string}
     * @memberof ConsentSaveInput
     */
    'formId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsentSaveInput
     */
    'referenceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConsentSaveInput
     */
    'referenceType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ConsentSaveInput
     */
    'flowId'?: number | null;
    /**
     * 
     * @type {Array<ConsentDataDetailSave>}
     * @memberof ConsentSaveInput
     */
    'consentDataDetails'?: Array<ConsentDataDetailSave> | null;
}

