/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.267
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmergencyContactInfoOutput
 */
export interface EmergencyContactInfoOutput {
    /**
     * 
     * @type {number}
     * @memberof EmergencyContactInfoOutput
     */
    'emergencyContactId'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmergencyContactInfoOutput
     */
    'customerId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactInfoOutput
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactInfoOutput
     */
    'relationshipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactInfoOutput
     */
    'relationshipDesc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactInfoOutput
     */
    'relationshipOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactInfoOutput
     */
    'mobile'?: string | null;
}

