/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.242
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAccountByRefIdOutput
 */
export interface GetAccountByRefIdOutput {
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'accountNo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetAccountByRefIdOutput
     */
    'suitScore'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'suitDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'fatcaFlag'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetAccountByRefIdOutput
     */
    'creditLine'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'atsFlag'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'atsBackCd'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'atsBankAcctNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'kycExpiredDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'birthDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByRefIdOutput
     */
    'email'?: string | null;
}

