/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.242
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HistoriesOutput
 */
export interface HistoriesOutput {
    /**
     * 
     * @type {string}
     * @memberof HistoriesOutput
     */
    'action'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HistoriesOutput
     */
    'actionBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HistoriesOutput
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HistoriesOutput
     */
    'remark'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HistoriesOutput
     */
    'actionTimestamp'?: string | null;
}

