/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.267
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MasterATSBankOutput
 */
export interface MasterATSBankOutput {
    /**
     * 
     * @type {string}
     * @memberof MasterATSBankOutput
     */
    'bankCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MasterATSBankOutput
     */
    'bankShortName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MasterATSBankOutput
     */
    'bankNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MasterATSBankOutput
     */
    'bankNameEn'?: string | null;
}

