/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.267
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OccupationInfoModel } from './occupation-info-model';

/**
 * 
 * @export
 * @interface OccupationInfoResponse
 */
export interface OccupationInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof OccupationInfoResponse
     */
    'corporateId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OccupationInfoResponse
     */
    'referenceId'?: string | null;
    /**
     * 
     * @type {OccupationInfoModel}
     * @memberof OccupationInfoResponse
     */
    'occupationInfo'?: OccupationInfoModel | null;
}

