/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.267
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalInfoRequest
 */
export interface PersonalInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'personTypeCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'personTypeDesc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'referenceTypeDesc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'referenceID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'countryNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'countryNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'nationalityCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'nationDesc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'identityExpireDate'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PersonalInfoRequest
     */
    'identityNeverExpire'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleCodeTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'firstNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'lastNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'firstNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'lastNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'genderCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'gender'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'birthDate'?: string | null;
}

