/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.242
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalInfoRequest
 */
export interface PersonalInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleCodeTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'firstNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'lastNameTh'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleCodeEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'titleNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'firstNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'lastNameEn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'genderCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'nationalityCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'identityType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'identityNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'identityExpireDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'occupationCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'jobTypeCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'jobPosition'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PersonalInfoRequest
     */
    'income'?: number;
    /**
     * 
     * @type {number}
     * @memberof PersonalInfoRequest
     */
    'incomeOther'?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'incomeSourceOther'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoRequest
     */
    'incomeSourceOversea'?: string | null;
}

