/* tslint:disable */
/* eslint-disable */
/**
 * KYC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AmloSearchInput
 */
export interface AmloSearchInput {
    /**
     * 
     * @type {string}
     * @memberof AmloSearchInput
     */
    'refId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmloSearchInput
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmloSearchInput
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmloSearchInput
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmloSearchInput
     */
    'amloType'?: string | null;
}

