/* tslint:disable */
/* eslint-disable */
/**
 * KYC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApplicantResponseApplicantResponsePagination } from './applicant-response-applicant-response-pagination';

/**
 * 
 * @export
 * @interface ApplicantResponseApplicantResponsePaginationDataResponse
 */
export interface ApplicantResponseApplicantResponsePaginationDataResponse {
    /**
     * 
     * @type {number}
     * @memberof ApplicantResponseApplicantResponsePaginationDataResponse
     */
    'status'?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ApplicantResponseApplicantResponsePaginationDataResponse
     */
    'errors'?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicantResponseApplicantResponsePaginationDataResponse
     */
    'message'?: string | null;
    /**
     * 
     * @type {ApplicantResponseApplicantResponsePagination}
     * @memberof ApplicantResponseApplicantResponsePaginationDataResponse
     */
    'data'?: ApplicantResponseApplicantResponsePagination;
}

