/* tslint:disable */
/* eslint-disable */
/**
 * KYC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ComplianceInput
 */
export interface ComplianceInput {
    /**
     * 
     * @type {number}
     * @memberof ComplianceInput
     */
    'applicantId'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceInput
     */
    'isMonetarySource'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceInput
     */
    'isEstablishedPurpose'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceInput
     */
    'isFinancialCredibility'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ComplianceInput
     */
    'verifyIc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComplianceInput
     */
    'reasonIc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComplianceInput
     */
    'verifyManager'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ComplianceInput
     */
    'reasonManager'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceInput
     */
    'isApproved'?: boolean | null;
}

