/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.330
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnswerInput,
  AnswerListDataResponse,
  QuestionsOutputDataResponse,
} from '../models';
import {
    AnswerInputFromJSON,
    AnswerInputToJSON,
    AnswerListDataResponseFromJSON,
    AnswerListDataResponseToJSON,
    QuestionsOutputDataResponseFromJSON,
    QuestionsOutputDataResponseToJSON,
} from '../models';

export interface KnowledgeAssessmentsAnswersCorporateIdGetRequest {
    corporateId: string;
    xPortalToken?: string;
}

export interface KnowledgeAssessmentsQuestionsGetRequest {
    xPortalToken?: string;
}

export interface KnowledgeAssessmentsSaveCorporateIdPostRequest {
    corporateId: string;
    xPortalToken?: string;
    answerInput?: Array<AnswerInput>;
}

/**
 * 
 */
export class KnowledgeAssessmentsApi extends runtime.BaseAPI {

    /**
     * Retrieves answers for a knowledge assessment or suitability test based on a specific flow ID.
     */
    async knowledgeAssessmentsAnswersCorporateIdGetRaw(requestParameters: KnowledgeAssessmentsAnswersCorporateIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnswerListDataResponse>> {
        if (requestParameters.corporateId === null || requestParameters.corporateId === undefined) {
            throw new runtime.RequiredError('corporateId','Required parameter requestParameters.corporateId was null or undefined when calling knowledgeAssessmentsAnswersCorporateIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPortalToken !== undefined && requestParameters.xPortalToken !== null) {
            headerParameters['x-portal-token'] = String(requestParameters.xPortalToken);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/KnowledgeAssessments/Answers/{corporateId}`.replace(`{${"corporateId"}}`, encodeURIComponent(String(requestParameters.corporateId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerListDataResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves answers for a knowledge assessment or suitability test based on a specific flow ID.
     */
    async knowledgeAssessmentsAnswersCorporateIdGet(requestParameters: KnowledgeAssessmentsAnswersCorporateIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnswerListDataResponse> {
        const response = await this.knowledgeAssessmentsAnswersCorporateIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves questions for a knowledge assessment or suitability test.
     */
    async knowledgeAssessmentsQuestionsGetRaw(requestParameters: KnowledgeAssessmentsQuestionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionsOutputDataResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xPortalToken !== undefined && requestParameters.xPortalToken !== null) {
            headerParameters['x-portal-token'] = String(requestParameters.xPortalToken);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/KnowledgeAssessments/Questions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionsOutputDataResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves questions for a knowledge assessment or suitability test.
     */
    async knowledgeAssessmentsQuestionsGet(requestParameters: KnowledgeAssessmentsQuestionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionsOutputDataResponse> {
        const response = await this.knowledgeAssessmentsQuestionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Saves answers for a knowledge assessment or suitability test based on a specific flow ID.
     */
    async knowledgeAssessmentsSaveCorporateIdPostRaw(requestParameters: KnowledgeAssessmentsSaveCorporateIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnswerListDataResponse>> {
        if (requestParameters.corporateId === null || requestParameters.corporateId === undefined) {
            throw new runtime.RequiredError('corporateId','Required parameter requestParameters.corporateId was null or undefined when calling knowledgeAssessmentsSaveCorporateIdPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xPortalToken !== undefined && requestParameters.xPortalToken !== null) {
            headerParameters['x-portal-token'] = String(requestParameters.xPortalToken);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/KnowledgeAssessments/Save/{corporateId}`.replace(`{${"corporateId"}}`, encodeURIComponent(String(requestParameters.corporateId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.answerInput.map(AnswerInputToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerListDataResponseFromJSON(jsonValue));
    }

    /**
     * Saves answers for a knowledge assessment or suitability test based on a specific flow ID.
     */
    async knowledgeAssessmentsSaveCorporateIdPost(requestParameters: KnowledgeAssessmentsSaveCorporateIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnswerListDataResponse> {
        const response = await this.knowledgeAssessmentsSaveCorporateIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
