########################################################
### Open API Config file
### - Using root path perspective
########################################################

generatorName: typescript-axios
outputDir: ./src/services/rest-api/???
inputSpec: https://__url__/swagger/develop/swagger.json
apiPackage: "entity"
modelPackage: "model"
enumPropertyNaming: "UPPERCASE"
stringEnums: false
supportsES6: true
useSingleRequestParameter: true
withSeparateModelsAndApi: true